name: deploy project
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: run tests
        run: npm test
      - name: run build
        run: npm run build
      - name: Deploy project
        run: echo "Deploying"
